"""Add index for fast feed sorting

Revision ID: 006_fast_sorting_index
Revises: 005_guest_users
Create Date: 2026-08-20 00:54:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006_fast_sorting_index'
down_revision = '005_guest_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watchlist_matches_sorting', 'watchlist_matches', ['watchlist_id', 'match_score', 'matched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_matches_sorting', table_name='watchlist_matches')
    # ### end Alembic commands ###
